### PR TITLE
Allow a retention policy to be passed when writing points.

### PR DESCRIPTION
**Pull request by recurser**
I'm not sure if `Writer::Async` should implement this as well - it doesn't look like it (?).

### CODE REVIEW

**Comment by johnfox** [comment]
+1 for  the ability to specify retention policy on write

**Comment by toddboom** [comment]
@recurser Would you mind adding a quick snippet to the README to document this? I'll try to get this merged and cut a new release tomorrow. Thanks!

**Comment by recurser** [comment]
Apologies for the delay @toddboom - I've updated README.

**Comment by toddboom** [comment]
@recurser awesome, thanks!

**Pull request merged**
