### PR TITLE
string values must be quoted

### PR DESCRIPTION
**Pull request by williampratt**
Writes were failing because string values weren't quoted.

### CODE REVIEW

**Comment by mcastilho** [comment]
@williampratt  You need to escape double-quotes if present in the string also. I am not sure you are suppose to escape commas on the key...

**Comment by williampratt** [comment]
Escaping Characters
If a measurement, tag key, tag value, or field key contains a space or a comma , it must be escaped using the backslash character \.

I escape quotes now on values as well.

**Comment by williampratt** [comment]
This is a show stopper for anyone using string values in 0.9.x. Can we get this merged quickly? It wasn't caught in the specs because the specs use #dump and don't hit an actual influx server. 

Thanks!

**Comment by toddboom** [comment]
@williampratt merging now! i'll try to get a gem cut this weekend. any other issues that you think need to be addressed?

**Comment by williampratt** [comment]
No, so far I haven't found any. I'll definitely let you know.

**Pull request merged**
